init

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -8,32 +8,32 @@ pipeline {
                 sshagent(['manjaro']) {
                     sh """
                         ssh -o StrictHostKeyChecking=no -p 22 ubuntu@3.106.223.225 '
-                        mkdir -p ~/Code/CICD
-                        cd ~/Code/CICD
-                        if [ -d "test-jenskin" ]; then
-                        echo "Project already exists. Updating from GitHub..."
-                        cd test-jenskin
-                        git fetch
-                        git reset --hard origin/main
-                        git pull origin main
-                    else
-                        echo "Project does not exist. Cloning from GitHub..."
-                        git clone https://github.com/cavaldos/test-jenskin.git
-                        cd test-jenskin
-                        git checkout main
-                    fi
-  # Install dependencies and run commands
-npm install
-npm run test || true  # Continue even if tests fail
-npm run build
-docker-compose -f docker-compose.yml down
-docker-compose -f docker-compose.yml build
-docker-compose -f docker-compose.yml up -d
-                
+                            mkdir -p ~/Code/CICD
+                            cd ~/Code/CICD
+                            if [ -d "test-jenskin" ]; then
+                                echo "Project already exists. Updating from GitHub..."
+                                cd test-jenskin
+                                git fetch
+                                git reset --hard origin/main
+                                git pull origin main
+                            else
+                                echo "Project does not exist. Cloning from GitHub..."
+                                git clone https://github.com/cavaldos/test-jenskin.git
+                                cd test-jenskin
+                                git checkout main
+                            fi
+                            
+                            # Install dependencies and run commands
+                            npm install
+                            npm run test || true  # Continue even if tests fail
+                            npm run build
+                            docker-compose -f docker-compose.yml down
+                            docker-compose -f docker-compose.yml build
+                            docker-compose -f docker-compose.yml up -d
+                        '
                     """
                 }
             }
-
         }
     }
 }
